### GraphQL - authorize payment
POST http://localhost:8080/graphql
Content-Type: application/json

{
  "query": "mutation Authorize($input: AuthorizePaymentInput!) { authorizePayment(input: $input) { id merchantId orderId customerId amount currency status createdAt updatedAt } }",
  "variables": {
    "input": {
      "merchantId": "mrc_001",
      "orderId": "ord_1001",
      "customerId": "cus_9001",
      "amount": 149.90,
      "currency": "PEN"
    }
  }
}

### GraphQL - find by merchant
POST http://localhost:8080/graphql
Content-Type: application/json

{
  "query": "query { paymentsByMerchant(merchantId: \"mrc_001\") { id orderId amount currency status } }"
}
